App\Entity\Blade:
  properties:
    name:
      - NotBlank: ~
      - Length:
          min: 2
    rareness:
      - NotBlank: ~
      - Type:
          type: integer
      - Range:
          min: 1
          max: 6
    weapon:
      - NotNull: ~
    element:
      - NotNull: ~
    strength:
      - Type:
          type: integer
      - Range:
          min: 0
    trustLevel:
      - Type:
          type: integer
      - Range:
          min: 1
          max: 5
    skills:
      - Valid: ~